apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotit-app
  template:
    metadata:
      labels:
        app: spotit-app
    spec:
      containers:
        - name: spotit-app
          image: ghcr.io/spotit-app/spotit-app:main
          resources:
            limits:
              memory: "512Mi"
              cpu: "2000m"
          env:
            - name: IMAGEKIT_URL
              valueFrom:
                secretKeyRef:
                  name: spotit-secret
                  key: imagekit-url
            - name: IMAGEKIT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: spotit-secret
                  key: imagekit-private-key
            - name: OAUTH2_ISSUER
              valueFrom:
                secretKeyRef:
                  name: spotit-secret
                  key: oauth2-issuer
            - name: OAUTH2_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: spotit-secret
                  key: oauth2-audience
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spotit-secret
                  key: postgres-username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spotit-secret
                  key: postgres-password
            - name: IMAGEKIT_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: spotit-config
                  key: imagekit-public-key
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: spotit-config
                  key: datasource-url
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: spotit-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: spotit-config
                  key: redis-port
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spotit-config
                  key: spring-profiles-active
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spotit-app
spec:
  selector:
    app: spotit-app
  ports:
    - port: 8080
      targetPort: 8080
