import { lazy } from 'react';
export const ForeignLanguages = lazy(() => import('./Profile/ForeignLanguages'));
export const PersonalData = lazy(() => import('./Profile/PersonalData'));
export const Experience = lazy(() => import('./Profile/Experience'));
export const SoftSkills = lazy(() => import('./Profile/SoftSkills'));
export const TechSkills = lazy(() => import('./Profile/TechSkills'));
export const ProtectedPage = lazy(() => import('./ProtectedPage'));
export const Interests = lazy(() => import('./Profile/Interests'));
export const Education = lazy(() => import('./Profile/Education'));
export const PageNotFound = lazy(() => import('./PageNotFound'));
export const Projects = lazy(() => import('./Profile/Projects'));
export const Courses = lazy(() => import('./Profile/Courses'));
export const Socials = lazy(() => import('./Profile/Socials'));
export const Other = lazy(() => import('./Profile/Other'));
export const Profile = lazy(() => import('./Profile'));
export const Home = lazy(() => import('./Home'));
